### ISSUE TITLE
How to hide the panels until hover or clicked?

### ISSUE THREAD

**Issue by ollie007** [scotch-io/scotch-panels#45]
How to hide the panels until hover or clicked?

would like an option to hide the panel unless its required

    display:hidden

would it be revealed by this script?

**Comment by seanhudson** [comment]
Did you ever get this fixed? It doesn't look like anyone has responded in a while.

**Comment by whatnickcodes** [comment]
Just use basic jQuery for this:

```css
.my-panel-name {
    opacity: 0; /* or display: none; or visibility: hidden; */
}
.my-panel-name.show {
    opacity: 1; /* or "display: block;" or "visibility: visible;" */
}
```

```javascript
// On hover
$('.on-hover-of-something').hover(function() {
     $('.my-panel-name').addClass('show');
});

// On DOM ready
$(function() {
     $('.my-panel-name').addClass('show');
});

// On Page Load
$(window).load(function() {
     $('.my-panel-name').addClass('show');
});

```
